version: '3.8'
services:
  postgresdb:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dblaetfood
    ports:
      - '5432:5432'
